### ISSUE TITLE
Model Checkpoint viT5-base

### ISSUE THREAD

**Issue by r1ckC139** [vietai/ViT5#1]
Hi there,
I have a issue with your viT5-base model on huggingface, when i run [script viT5-base](https://huggingface.co/VietAI/vit5-base) for task summarization, output just a random sequence,  I think you uploaded the wrong model checkpoint for viT5-base.

**Comment by justinphan3110** [comment]
Hi @r1ckC139 , you can use [Finedtune models](https://huggingface.co/VietAI/vit5-large-vietnews-summarization) to run summarization

**Comment by heraclex12** [comment]
Hi,

I assume that you're using our pretrained language model [ViT5-base](https://huggingface.co/VietAI/vit5-base) for summarization. Pretrained language models are just trained on large-scale corpora to learn general-purpose representations. They need to be finetuned on downstream tasks such as summarization to give a better representation.

**Comment by r1ckC139** [comment]
Hi @heraclex12, @justinphan3110 
The script you guys published on hugging face make me confuse, I thought the model was fine-tuned for the summary task but it was not. Anyway, Thank you so much for your quick response.

**Comment by r1ckC139** [comment]
Hi @heraclex12,
As far as I understand, T5 is trained using the span-corruption objective, I tried to create a sample similar to the training data, and the result is still just a random sequence. Is there any way (or task) to try vi-T5 base without fine-tune step to see how effective T5 is ?
(This problem only occurs in viT5-base version, large version seems to work well )
**Span-corruption objective**
![image](https://user-images.githubusercontent.com/61724310/173552111-2113fd76-4120-4bfe-8476-afee2058dc86.png)
**My code test viT5-base**
![image](https://user-images.githubusercontent.com/61724310/173552290-cd158a87-ed7e-437d-a2b6-4ff58bf20b8c.png)
**Result test on large version**
![image](https://user-images.githubusercontent.com/61724310/173553208-4294e284-e1fe-4bdf-b77e-8f5656f1fc8d.png)
