### ISSUE TITLE
Pretraining

### ISSUE THREAD

**Issue by haisonle001** [vietai/ViT5#11]
Hi, 

I want to pretrain viT5 on another Vietnamese dataset (P3 dataset, for example). Can I have the pretraning script your team use to pretrain on CC100?

Thank you in advance.

**Comment by justinphan3110** [comment]
We migrated all pretraining scripts to another branch as it can be outdated. You can take a look at it here:
https://github.com/vietai/ViT5/tree/mesh_tf1/pretraining_mesh

**Comment by enpassanty** [comment]
I have a custom dataset that I need to pretrain and then finetune with long context (16.384).  I was thinking of using some of your pretraining scripts above but adapting them for [longT5](https://huggingface.co/docs/transformers/model_doc/longt5).  do you think this is doable?  do you have any advice on this?  thank you
