### ISSUE TITLE
viT5 base issue

### ISSUE THREAD

**Issue by r1ckC139** [vietai/ViT5#2]
Hi @heraclex12,
As far as I understand, T5 is trained using the span-corruption objective, I tried to create a sample similar to the training data, and the result is still just a random sequence. Is there any way (or task) to try vi-T5 base without fine-tune step to see how effective T5 is ?
This problem only occurs in viT5-base version, large version seems to work well.
(I create new issue make sure you guys can see it, because [issue 1](https://github.com/vietai/ViT5/issues/1) was closed)
**Span-corruption objective**
![image](https://user-images.githubusercontent.com/61724310/173552111-2113fd76-4120-4bfe-8476-afee2058dc86.png)
**My code test viT5-base**
![image](https://user-images.githubusercontent.com/61724310/173552290-cd158a87-ed7e-437d-a2b6-4ff58bf20b8c.png)
**Result test on large version**
![image](https://user-images.githubusercontent.com/61724310/173553208-4294e284-e1fe-4bdf-b77e-8f5656f1fc8d.png)

_Originally posted by @r1ckC139 in https://github.com/vietai/ViT5/issues/1#issuecomment-1154989427_

**Comment by heraclex12** [comment]
Hi @r1ckC139,

Thank you for your feedback. We have recently realized some problems with the base config and quickly fixed them. So from now, you can try to load the base model to make some predictions.

If you face any problems with our models, feel free to let us know.

Thank you!
