### ISSUE TITLE
Missmatch tensor size with vit5-large

### ISSUE THREAD

**Issue by Dean98AI** [vietai/ViT5#3]
![image](https://user-images.githubusercontent.com/77484083/182290915-dbce2b92-444f-4ae5-bc8d-40860f0f0622.png)
How to fix this error beacause i train with mT5 no appear error this ?
Thanks guys !

**Comment by heraclex12** [comment]
Hi @Dean98AI ,

Thank you for letting us know about this issue. There was something wrong with our config, but it was fixed now. You can try to load our large model again.
