### ISSUE TITLE
Hỏi về đánh giá checkpoint VietAI/vit5-large-vietnews-summarization trên dataset Vietnews? 

### ISSUE THREAD

**Issue by BinhMinhs10** [vietai/ViT5#4]
![Screenshot from 2022-08-19 07-48-36](https://user-images.githubusercontent.com/22696815/185530784-e14b69d1-b9a3-4416-aba0-7bd11d4df542.png)

mình thử evaluate trên dataset vietnew với code run_summarization của huggingface (đã set sourse_prefix "vietnews: " ) nhưng không hiểu sao rouge2, rougeL,.. rất thấp

**Comment by justinphan3110** [comment]
Hi @BinhMinhs10, can you share the scripts to reproduce this?

**Comment by BinhMinhs10** [comment]
https://github.com/huggingface/transformers/blob/main/examples/pytorch/summarization/run_summarization.py
Mình dùng script này bỏ mỗi đoạn nltk chỗ hàm postprocess_text

**Comment by BinhMinhs10** [comment]
Great, thanks to @justinphan3110 for pointing this out and suggesting a solution 🚀
