### ISSUE TITLE
What tokenizer use to token dataset ?

### ISSUE THREAD

**Issue by Dean98AI** [vietai/ViT5#5]
I want to know tokenizer used to preprocess data to train viT5 (vncorenlp, underthesea,...), Thanks guys !

**Comment by justinphan3110** [comment]
Hi @Dean98AI , we build our own sentence piece tokenizer that can be loaded with 

```[python3]
model_size = "base" # or large
tokenizer = AutoTokenizer.from_pretrained(f"VietAI/vit5-{model_size}")  
```

**Comment by Dean98AI** [comment]
Hi @justinphan3110 , so you don't use word segment to train ? My question is about preprocess data to train ( use word segment (vncorenlp, underthesea ,...? or don't use and use raw text), thank u guys

**Comment by heraclex12** [comment]
HI @Dean98AI,

We didn't use any word segmentation tools in preprocessing data. Raw texts were tokenized directly by our Sentencepiece tokenizer.

**Comment by Dean98AI** [comment]
Thanks u guys !
