### ISSUE TITLE
Fine tune vit5-base model for text summarization

### ISSUE THREAD

**Issue by MinhDang685** [vietai/ViT5#6]
Hello VietAI team,

Thanks for sharing the pretrained models in your research paper. I am interested on fine tuning the [VietAI/vit5-base](https://huggingface.co/VietAI/vit5-base) language model for the abstractive summarization task. I have some questions:
1. When I run your example [here](https://huggingface.co/VietAI/vit5-base), unlike @r1ckC139 in #1 that he has random sequences, I always got a fixed-length (=max_length) unchanged array, I have try to modify the input (with "vi: " / "vietnews: " prefix, and without prefix) but the result is not changed. Could you take a look?
![image](https://user-images.githubusercontent.com/27952830/188310705-dc6e3ea6-1bcb-438d-b74f-9af662b93d19.png)
2. In the fine tuning phase, do I need to preprocess the data by adding a prefix?

Thanks a lot

**Comment by justinphan3110** [comment]
Hi @MinhDang685 , for MLM pretraining we used [mesh-tensorflow](https://github.com/vietai/ViT5/blob/main/pretraining_mesh/train_envi_base.py). The models on HuggingFace are ready for finetuning only. 

You don't need to add prefix in finetunning.

**Comment by MinhDang685** [comment]
Hi @justinphan3110, thanks for your quick reply. 
- Since the model is trained with mesh-tensorflow, can I directly use it to finetune in PyTorch without any adaptation?
- Could you give [this issue](https://github.com/vietai/ViT5/issues/6#issue-1361126551) (that the model always generates an unchanged sequence) a look when you have time.

Thanks

**Comment by justinphan3110** [comment]
@MinhDang685 
- We have just published an example code for [finetunning with huggingface](https://github.com/vietai/ViT5/blob/main/finetunning_huggingface/finetune_vn_sum.ipynb)

- Can you double-check again if there is still a generated unchanged sequence issue?

**Comment by MinhDang685** [comment]
Hi @justinphan3110, thanks for your help, I try to generate with the model again and it works now, the output sequences now changes base on the input
I notice that you have updated the model [config.json](https://huggingface.co/VietAI/vit5-base/commit/ffd2f774884fc6be38a18e3f00b2ddeb0a89544b) file, is it the cause of the issue (that I miss the "summarization" prefix to the input to indicate I want the model to perform summarization task)?

**Comment by justinphan3110** [comment]
@MinhDang685 ,
 You need prefix `vietnews:` for `VietAI/vit5-large-vietnews-summarization` . 
For `VietAI/vit5-large-vietnews-summarization` you don't need any prefix.  

You can have a look over the [eval scripts with HuggingFace](https://github.com/vietai/ViT5/blob/main/eval/Eval_vietnews_sum.ipynb)

**Comment by MinhDang685** [comment]
thank you @justinphan3110 for pointing that out
